### ISSUE TITLE
When running multiple iterations, I get Windows Error 32: A file is being use by another process

### ISSUE THREAD

**Issue by annika-wsp** [HSLdevcom/helmet-model-system#101]
When running 10 iterations, the model seems to be running ok, but I get the following error between assignments, starting in later iterations of the model (in this example starting in iteration 9):

Traceback (most recent call last):
  File "C:\Program Files\INRO\Emme\Emme 4\Emme-4.3.6\python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "C:\Program Files\INRO\Emme\Emme 4\Emme-4.3.6\python27\lib\logging\handlers.py", line 350, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file log.py, line 61

See file for an example of model output to command prompt:
[Virheilmot_10_kierrosta.txt](https://github.com/HSLdevcom/helmet-model-system/files/3920839/Virheilmot_10_kierrosta.txt)

**Comment by atte-wsp** [comment]
Got the same error. I think this is due to the log file rollover at midnight. The handler tries to create backup copy, but the logging file is in use so it cannot be closed.  

Fix the issue:
1) Helmet app needs to release the log file for writing. Should check if the file is opened by Helmet multiple times? I checked that the file was not open in another program (notebook, etc.)

**Comment by zptro** [comment]
Not sure when, but I suppose this is fixed.
