### ISSUE TITLE
Transit costs and base demand assignment

### ISSUE THREAD

**Issue by atte-wsp** [HSLdevcom/helmet-model-system#169]
I was wondering if base demand car assignment should be done before transit cost calculation? Currently the transit assignment of cost calculations are done without any previous car assignments and speed of buses is dependent of link speeds produced by car assignment. I think this sets bus travel times infinite or zero, which could affect route choice.

However, I'm not sure how transit cost assignments is working and if this is a bug, so I won't create PR before comments.

**Comment by TimoElolahde** [comment]
Sounds reasonable. Generally, car assignment really is made before transit assignment because, as you wrote, the speeds of buses are dependent of car speeds (if there are no bus lanes on the street). I cannot see why transit cost calculation should be made before car assignment. Or other way round: what problems could moving transit cost calculation between car assignment and transit assignment cause?

**Comment by atte-wsp** [comment]
Resolved by performing aht car assignment before transit cost calculation. Base assignment should be later optimized, but it requires refactoring the Emme-assignment.
