### ISSUE TITLE
4verkkoa_HM40.mac does not have any option parameters

### ISSUE THREAD

**Issue by zptro** [HSLdevcom/helmet-model-system#201]
Previously, [batin_4verkkoa_M2019.mac](https://github.com/HSLdevcom/helmet-model-system/blob/569c54ea3e373b0b3d0514a8356f4a61591d5084/Database/batin_4verkkoa_M2019.mac) had some options to not run f-macros etc, which are missing from new [4verkkoa_HM40.mac](https://github.com/HSLdevcom/helmet-model-system/blob/51ff09c6474b41f83d0f0b39379c647fadcb8324/Database/4verkkoa_HM40.mac). The old macro also did some basic validation of networks. Should these be re-added?

**Comment by atte-wsp** [comment]
I replaced the options parameters with scenario number parameters, as Helmet 4.0 allows to run model with different scenario numbers (before constant 19-23). We have never used the options in our work, but just run all f-macros and pysakki-macros every time network is created. However I can add parameters if they are used by another end-users.

Network validation(tarkista_verkko.mac) could be added anyways. That's an useful addition.

**Comment by TimoElolahde** [comment]
For some reason Mervi ja Eeva wanted that there is a possibility not to run pysakki.mac and so called f-macros. I did not fully understand their arguments. Of course, skipping these phases speeds the run, but only marginally. 

In my opinion it was important to check during the run whether certain extra attributes needed later are defined. If this check can be done automatically the Y/N (or rather K/E) question is no more needed.

In my opinion it was also important to check in the beginning of the run that the user understands that running the macro batin_4verkkoa_M2019.mac deletes all contents of the scenarios from 19 to 23 including results of previous model run. Other parts of the macro run are not as fatal because everything else can be done again e.g. when some input file is missing or when there has been misspelling in parameters. If the key results are copied automatically to another scenario or output to external files during the model run the Y/N (or rather K/E) question may not be necessary any more.

Last summer I tried to write Python scripts which could replace batin macro run but they are not completed yet. The scripts are saved in branch TimoElolahde-patch-2.

**Comment by TimoElolahde** [comment]
New versions of 4verkkoa_HM40.mac and tarkista_verkko.mac saved in 
https://github.com/HSLdevcom/helmet-model-system/tree/TimoElolahde-patch-1
Y/N (or rather K/E) questions are not used.

**Comment by TimoElolahde** [comment]
I edited the files 4verkkoa_HM40.mac and tarkista_verkko.mac outside GitHub and only uploaded the new versions in GitHub, so they seem to be totally different compared to previous versions. However, all lines are not changed in the macros. The most essential changes made are described in comments. Only these two macro files are modified. All other files in my branch are older than in master branch.
