### ISSUE TITLE
Zonedata must be in ascending order

### ISSUE THREAD

**Issue by samulikyytsonen** [HSLdevcom/helmet-model-system#222]
Some python scripts handle the zonedata (.pop, wrk., etc) based on the order of vectors instead of reading the zone number from first column. I think the issue occurs in freight.py and in some trip generation scripts.

Usually pop and wrk files are modified in projects and wrong order may give unexpected results without warning.

**Comment by zptro** [comment]
Important observation! Most modules handle raw numpy arrays for performance reasons, so the order of the data is indeed important. As I see it, there are two possible solutions to this:
- Check if the data from files is ordered and throw an error otherwise
- Always sort data when importing

When checking this, I also realised that duplicates in indata do not throw any error. Should fix this as well.
