### ISSUE TITLE
Additional zones should be added to cost_peripheral.omx?

### ISSUE THREAD

**Issue by samulikyytsonen** [HSLdevcom/helmet-model-system#247]
The assignment crashes in the first iteration (Helmet 4.0.2) because the shape of cost_peripheral matrix is wrong. Matrix check is passed, and warning of additional zones is given. I wonder if this happened just for me?

**Comment by zptro** [comment]
You are right, I had not thought of the cost_peripheral matrix when informing about the matrix validation update.

We cannot add zeros to this matrix as that would affect destination and mode choice in a unwanted way. So in a way, this crash behavior is necessary. You will have to copy costs from some other zones manually in this file.

I think the long term solution to this problem is to aggregate the cost_peripheral file to municipality level and disaggregate it in the code, similarly to the external demand matrices. This is roughly the level of detail when creating this data anyway. But we need to maintain backwards compatibility with the current file format as well.
