### ISSUE TITLE
Demands are not saved correctly on text files?

### ISSUE THREAD

**Issue by samulikyytsonen** [HSLdevcom/helmet-model-system#291]
Helmet model system v.4.0.4 prints totally different values to origins_demand, origins_shares and mode_shares text files than previous model version. E.g. zone 101 has 56% transit mode share with previous version and 14% with the new release. 

Quickly I can't say reason for this. Other files, e.g. origin_demand_areas.txt, seem to give same results as previous model.

**Comment by zptro** [comment]
Sorry, I should have highlighted this change (which was implemented in https://github.com/HSLdevcom/helmet-model-system/pull/244/commits/32108c2ceced1917156b5eae9a90826fb0590dbd) in the 4.0.4 release! 

Previously the shares included tour attractions (which are very large for zone 101), but from 4.0.4 on, they include only tours **generated** in the area. Because zone 101 is dominated by workplaces, most tours generated there are work-based (or other-based), and work-based tours (business errands, lunch breaks, etc.) are predominantly walk tours in the city center.
