### ISSUE TITLE
Mode `h` is removed from some links in network

### ISSUE THREAD

**Issue by johpiip** [HSLdevcom/helmet-model-system#476]
When running a model, mode `h` is removed from links where mode is originally:

- ha
- haf
- hbgdeaf
- hbgde
- hrj
- ht
- htp

(Testing in test network where I added `h` mode to all links.)

This does not seem to affect end results: test network results are about the same, when the model run starts with `h`'s as without `h`'s. (Some decimal changes happen though...) So my issue really is: what is the point of having `h` on the network if the scripts work without it? Or do they really?

Links with and without `h` are handled here for bike:
https://github.com/HSLdevcom/helmet-model-system/blob/fbd9b73f663d4bead4ae821cf00a54f39fd1a835/Scripts/assignment/assignment_period.py#L369-L372

And here for car (and transit?):
https://github.com/HSLdevcom/helmet-model-system/blob/fbd9b73f663d4bead4ae821cf00a54f39fd1a835/Scripts/assignment/assignment_period.py#L337-L340

I think that because `_set_car_and_transit_vdfs()` is run after `_set_bike_vdfs()`, it drops `h`'s because there is no `c` in the modes, so it drops them and does `publish_network()`.

**Comment by zptro** [comment]
To be able to import turn restrictions (when initializing the network in Emme) for cars, the main auto mode (i.e., `h`) for some reason needs to be defined on in-coming and out-going links. In practice, this is only necessary for car (`c`) links. because we do not have any turn restrictions for bikes. However, it is really easy to add `h` on all links in Modeller compared to adding it only on links where `c` is allowed. As you point out, the result is the same when running Helmet.

**Comment by johpiip** [comment]
What a quick response! 😄 Oookay. I think I need to add some debug messages or rethink what should be published to the network, because it does not seem intuitive that a model run changes the network properties. Thank you very much for clarification!
