### ISSUE TITLE
Why was pedestrian assignment taken off from the iterations?

### ISSUE THREAD

**Issue by hsl-petrhaj** [HSLdevcom/helmet-model-system#543]
Wouldn't it make sense at least in the last iteration?
I think some consultants have used it before.
@zptro
@johpiip

**Comment by zptro** [comment]
Pedestrian assignment is done in the first iteration in order to calculate walk accessibility to workplaces and services. However, pedestrian route choices have never been validated and the network has not been developed to cater for such validation. Moreover, a large share of pedestrian demand is within the zone, so it does not cause any assignable flows.

I would argue that pedestrian assignment would require a much more fine-grained zone system and more detailed network. And that has been regarded as a task that has not been assigned to HSL by the municipalities.

**Comment by hsl-petrhaj** [comment]
Thanks, Jens. 
Regarding the relevance, about 30 % of walking trips are over 1 km (source: HLT), so even with our not-so-finegrained zoning they would appear on the network, except for some sub/exurban setting. I get the point about validation and not being on the task list from the municipalities.
